### ISSUE TITLE
rectangular copy should trim trailing whitespace on each line

### ISSUE THREAD

**Issue by cjw296** [jumptrading/FluentTerminal#76]
subject says it all really

**Comment by MaxRis** [comment]
I believe that we can trim whitespaces on Fluent's side.
Doing it in xterm looks error prone https://github.com/xtermjs/xterm.js/issues/1286 and pretty scary
cc: @peske

**Comment by MaxRis** [comment]
Can confirm that difference in behavior between Fluent and cmd.exe exists: copying of multilines text which line ends with white spaces results in white spaces removing by cmd.exe, but Fluent keeps whitespaces on copying to clipboard.

@felixse Fluent receives white spaces from xterm's selection changed event, but it looks like by design for xterm https://github.com/microsoft/vscode/issues/43696

@felixse @peske what do you think about new Fluent's optional settings to trim whitespaces before line ending symbol on copy to clipboard?

**Comment by MaxRis** [comment]
cc: @mjs

**Comment by peske** [comment]
Not sure about this one. Which code currently adds text to the clipboard? xterm.js?

If so your plan is to change the clipboard content from Fluent (C#)?

**Comment by MaxRis** [comment]
@peske xterm.js only sends an `selectionChanged` event with selected text. Working with clipboard happens on Fluent's side https://github.com/jumptrading/FluentTerminal/blob/master/FluentTerminal.App/Views/XtermTerminalView.xaml.cs#L233

The plan is that Fluent should modify on its own what it receives from xterm.js .
But we need to think if we can handle following issue appeared in https://github.com/microsoft/vscode/issues/43696 : 

![36229584-aac6c74c-11cf-11e8-9ef2-7d5e4ab26d2f](https://user-images.githubusercontent.com/1928902/60004073-9879c280-9674-11e9-9830-cb535ffe9eb4.png)

**Comment by peske** [comment]
Oh, in this case it's easy - just `RTrim()` every line before putting the text in the clipboard.

**Comment by MaxRis** [comment]
@peske but what do you think about an issue at above screenshot? It will appear once we will do RTrim. cc: @cjw296

**Comment by MaxRis** [comment]
Seems the issue happens only if ConPTY is enabled for terminal session

**Comment by peske** [comment]
It happens with ConPTY, but it looks for reason (by design): to avoid bug https://github.com/microsoft/vscode/issues/43696

**Comment by peske** [comment]
Btw. bug https://github.com/microsoft/vscode/issues/43696 may happen whenever we are using WinPTY.

**Comment by daviesalex** [comment]
That bug is fixed, right? https://github.com/xtermjs/xterm.js/pull/1775

**Comment by MaxRis** [comment]
@daviesalex yes, there were a lot changes in xterm.js related to RTrim

**Comment by peske** [comment]
At the moment this bug is still in xterm.js we are using (I've just tested). Maybe the fix will come with the next release. Or since we are using fork created by @MaxRis - maybe we can jump to their HEAD?

**Comment by daviesalex** [comment]
Looks like their HEAD is pretty close to the next release (v4) so might be good to generate a MSI built against this for testing - if this bug just goes away we know the fix will naturally come:
https://github.com/xtermjs/xterm.js/issues/2143
Remaining tasks (mostly look like docs/polish): https://github.com/xtermjs/xterm.js/issues?q=is%3Aopen+is%3Aissue+milestone%3A4.0.0

**Comment by MaxRis** [comment]
"fix trimming of right side" https://github.com/xtermjs/xterm.js/pull/1775 is resolved in v. 3.10.0. And we're current at v.3.14.1.
Going to try to understand the difference of behavior between ConPTY and WinPTY for xterm.js

**Comment by MaxRis** [comment]
Can confirm that ConPTY on Windows 1809 sends different escape sequences from what old WinPTY sends on white-spaces at the right side of terminal's line. It's very likely the reason why xterm.js processes text selection (action that priors copy action).

Input text: `test[SPACE_CHAR][SPACE_CHAR][SPACE_CHAR][SPACE_CHAR][SPACE_CHAR][SPACE_CHAR]`

WinPTY: `[0;33;93mt[0m[0K[?25h[0;33;93me[0m[0K[0;33;93ms[0m[0K[0;33;93mt[0m[0K[23G[24G[25G[26G[27G[28G`

ConPTY: `[181X[181C[4;14H[?25h[?25lt [?25h[HM[4;15H[?25le [?25h[HM[4;16H[?25ls [?25h[HM[4;17H[?25lt [?25h[HM[4;18H[?25l  [?25h[HM[4;19H[?25l  [?25h[HM[4;20H[?25l  [?25h[HM[4;21H[?25l  [?25h[HM[4;22H`

**Comment by MaxRis** [comment]
Also it was noticed extra space symbol issue only in ConPTY on copy/paste of whole whole terminal line.
It's known issue https://github.com/microsoft/terminal/issues/1126 .
Confirming that on Windows 1903 above ConPTY issue is resolve and Fluent works correctly.

And on Windows 1903 WinPTY already produces different output for the same input text as above:
`[?25h[?25l[?25h[93mt[?25l[m[?25h[?25l[93mte[?25h[?25l[m[?25h[?25l[93m[26;18Htes[?25h[?25l[m[?25h[?25l[93m[26;18Htest[?25h[?25l[m[?25h[?25l[93m[26;18Htest[m [?25h[?25l[?25h[?25l[93m[26;18Htest[m  [?25h[?25l[?25h[?25l[93m[26;18Htest[m   [?25h[?25l[?25h[?25l[93m[26;18Htest[m    [?25h[?25l[?25h[?25l[93m[26;18Htest[m     [?25h[?25l[?25h[?25l[93m[26;18Htest[m      [?25h`

**Comment by MaxRis** [comment]
So far:
- Whitespaces are trimmed for each line on rectangular copy under WinPTY, but not trimmed under ConPTY.
- Ubuntu and MacOS Terminals doesn't RTrim copied lines, but iTerm2 does.

Seems makes sense to implement right trimming on rectangular selection as Settings option.

**Comment by MaxRis** [comment]
Request to start discussion to have rtrim option directly in Xterm.JS was created there https://github.com/xtermjs/xterm.js/issues/2280

@cjw296 Fluent starts to support the feature from build 1.1.241. Could you please provide your feedback, thanks!

**Comment by cjw296** [comment]
Sorry, @MaxRis , only just saw your comment above.
The rtim seems to be working well, *except* on the last line of a rectangular copied block, which has a bunch of trailing whitespace still.

**Comment by MaxRis** [comment]
>  except on the last line of a rectangular copied block, which has a bunch of trailing whitespace still.

@cjw296 , unfortunately, can't repro the issue (have tried all combinations I was able to come up with).
Could you please provide more details: sample of copied content, running shell details, is ConPTY turned on, etc. Maybe, screenshot will help as well. Thank you

**Comment by cjw296** [comment]
I can repro using an ssh profile, mosh: no, conpty: yes to linux box.
`ls` and then copy the resulting text all lines, except the last one, are correctly rtrim'ed.

I can't try with conpty off as a result of #219

**Comment by cjw296** [comment]
-> low priority
